---
- name: "init_install"
  hosts: localhost
  gather_facts: true

  tasks:
    - name: "install apps"
      become: true
      block:

        #yumの代わりにaptを使う。
        - name: "apt update"
          ansible.builtin.apt:
            name: "*"
            state: present

        - name: "install apps"
          ansible.builtin.apt:
          #Docker公式リポジトリの情報を更新する。
            update_cache: true
            name:
#              - epel-release
#              - yum-utils
#              - python3-devel
              - python3-dev
#              - python3-libs #python3-lib2to3はインストール済み。
              - python3-setuptools #インストール済み。
              - bash-completion #インストール済み。
              - tmux #インストール済み。
              #Docker公式のインストールパッケージに準拠。
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

        - name: "Start service docker"
          service:
            name: docker
            state: started
            enabled: true

        - name: "add user to docker group"
          user:
            name: "{{ ansible_env.USER }}"
            groups: docker
            append: true

    #virtualenvによる仮想環境の作成は不要。

    - name: "list dotfiles"
      find:
        paths: "{{ playbook_dir }}/dotfiles"
        hidden: true
      register: file_list

    - name: "make link"
      file:
        src: "{{ item.path }}"
        path: "{{ ansible_env.HOME }}/{{ item.path | basename }}"
        state: link
        force: true
      with_items: "{{ file_list.files }}"

    - name: "cp ansible.cfg to home"
      copy:
        src: "{{ playbook_dir }}/ansible.cfg"
        dest: "{{ ansible_env.HOME }}/.ansible.cfg"
        mode: 0755
