---
- name: "init_install"
  hosts: localhost
  gather_facts: true

  tasks:
    - name: "install apps"
      become: true
      block:

        - name: "dnf update"
          ansible.builtin.dnf:
            name: "*"
            state: present

        - name: "install apps"
          ansible.builtin.dnf:
          #Docker公式リポジトリの情報を更新する。
            update_cache: true
            name:
              - python3-setuptools #インストール済み。
              - bash-completion #インストール済み。
              - tmux #インストール済み。
              #Docker公式のインストールパッケージに準拠。
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

        - name: "Start service docker"
          service:
            name: docker
            state: started
            enabled: true

        - name: "add user to docker group"
          user:
            name: "{{ ansible_env.USER }}"
            groups: docker
            append: true

    #virtualenvによる仮想環境の作成は不要。

    - name: "cp ansible.cfg to home"
      copy:
        src: "{{ playbook_dir }}/ansible.cfg"
        dest: "{{ ansible_env.HOME }}/.ansible.cfg"
        mode: 0755

    - name: 
