---
- name: Exam3
  hosts: vyos02
  gather_facts: false

  tasks:
    - name: show interfaces
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: show_interfaces

    - name: show interfaces
      ansible.builtin.debug:
        var: show_interfaces.stdout_lines

    - name: Set description
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet eth1 description debug_exam
        save: true

    - name: After show interfaces
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: after_show_interfaces

    - name: after show interfaces
      ansible.builtin.debug:
        var: after_show_interfaces.stdout_lines
