---
- name: test
  hosts: localhost
  gather_facts: false

  tasks:
    # - name: "Debug route"
    #   ansible.builtin.command:
    #     cmd: "ping -c 1 10.0.0.2"
    #   register: res

    # - name: "Debug res"
    #   ansible.builtin.debug:
    #     msg: "{{ res }}"

    - name: "Debug route"
      ansible.builtin.command:
        cmd: "ip route"
      register: res

    - name: "Debug res"
      ansible.builtin.debug:
        msg: "{{ res }}"

    - name: "Debug route"
      ansible.builtin.command:
        cmd: "sleep 180"
