---
- name: Change link_bypass
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Before vrrp state
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: result

    - name: Debug before vrrp state
      ansible.builtin.debug:
        var: result.stdout_lines[0]

    - name: Change priority of vrrp
      vyos.vyos.vyos_config:
        lines:
          - "set high-availability vrrp group service_nw01 priority '50'"
          - "set high-availability vrrp group service_nw02 priority '50'"
        save: true
      when: inventory_hostname == 'vyos01'

    - name: After vrrp state
      vyos.vyos.vyos_command:
        commands: "show vrrp"
      register: result

    - name: Debug After vrrp state
      ansible.builtin.debug:
        var: result.stdout_lines[0]
