---
- name: Exam3
  hosts: host01 host02
  gather_facts: false

  tasks:
    - name: Make file
      ansible.builtin.file:
        path: /tmp/{{ item }}
        state: touch
      loop:
        - loop_test1.txt
        - loop_test2.txt
        