---
- name: Exam2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: When/loop
      ansible.builtin.debug:
        var: item
      loop:
        - 3
        - 10
        - 25
        - 140
        - 233
        - 350
      when:  item < 100
