---
- name: exam3
  hosts: all
  gather_facts: false

  tasks:
    - name: 
      vyos_command:
        commands:
          - show ip route
#        register: result
      when: inventory_hostname == 'vyos01' or inventory_hostname == 'vyos02'

#    - name: Vyos debug show commands
#      ansible.builtin.debug: 
#        var: result.stdout_lines