---
- name: Exam2
  hosts: ubuntu

  tasks:
    - name: Exam2 playbook
      ansible.builtin.debug:
        msg: "exam2 playbook test!!"
      when: "'RedHat' in ansible_distribution or 'Ubuntu' in ansible_distribution"
