---
- name: exam3
  hosts: all
  gather_facts: false

  tasks:
    - name: vyos show ip route
      vyos.vyos.vyos_command:
        commands:
          - show ip route

      when: inventory_hostname == 'vyos01' or inventory_hostname == 'vyos02'
