---
- name: Exam3
  hosts: all
  gather_facts: false

  tasks:
    - name: vyos only command
      vyos.vyos.vyos_command:
        commands:
          - show ip route
      when: inventory_hostname in ['vyos01','vyos02']