---
- name: Exam4
  hosts: all
  gather_facts: false

  tasks:
    - name: Make textfile
      ansible.builtin.file:
        path: /tmp/test_exam4.txt
        state: touch
        mode: '0644'
      register: result
      when: inventory_hostname == 'host01' 
    
    - name: Debug Success messages
      ansible.builtin.debug:
        msg: "make success text!"
      when: inventory_hostname == 'host01' and result is succeeded

