---
- name: Exam4
  hosts: all
  gather_facts: false

  tasks:
    - name: Make textfile
      ansible.builtin.file:
      path: /home/ec2-user/ansible_on_vyos/ansible_practice/06_condition/when_exam_4.yml


