---
- name: Exam4
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Check before interface description #任意の実施
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: result

    - name: Check before interface description debug #任意の実施
      ansible.builtin.debug:
        var: result.stdout_lines

    - name: Set descriptions
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet {{ item.ethernet }} description {{ item.description }}
      loop: 
        - { ethernet: 'eth1', description: 'loop_test1' }
        - { ethernet: 'eth2', description: 'loop_test2' }

    - name: Check after interface description #任意の実施
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: result

    - name: Check after interface description debug #任意の実施
      ansible.builtin.debug:
        var: result.stdout_lines
