---
- name: Exam1
  hosts: localhost
  gather_facts: false

  vars:
    fruits:
      - Apple
      - Banana
      - Peach

  tasks:
    - name: Debug fruits
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ fruits }}"
