---
- hosts: localhost
  gather_facts: false
  become: false

  tasks:
  - name: make file
    ansible.builtin.file:
      path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/exam3.txt
      state: touch

  - name: copy file
    ansible.builtin.copy:
      src: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/exam3.txt
      dest: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/copy_directory