---
- name: exam3
  hosts: vyos01
  gather_facts: false

  tasks:
    - name: show_interfaces
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: vyos01_show_interfaces

    - name: log_touch
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/vyos01_show_interfaces.log
        state: touch

    - name:  log_writing
      ansible.builtin.copy:
        content: "{{ vyos01_show_interfaces.stdout[0] }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/vyos01_show_interfaces.log