---
- name: Exam3
  hosts: vyos01
  gather_facts: false

  tasks:
    - name: Execute show interfaces
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: show_interfaces_output

    - name: Execute show ip toute
      vyos.vyos.vyos_command:
        commands:
          - show ip route
      register: show_ip_route_output

    - name: Write show ip route output to log
      copy:
        content: "{{ show_ip_route_output.stdout }}"
        dest: "/home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/vyos01_show_ip_route.log"
