---
- name: Exam2
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: make file
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/copy_file_exam2.txt
        state: touch
        mode: "0644"
    - name: copy file
      ansible.builtin.copy:
        src: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/copy_file_exam2.txt
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/copy_directory/copy_file_exam2.txt
        mode: "0755"