---
- name: Exam2-2
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Show commands before
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: result_before

    - name: Output text file in before_directory
      ansible.builtin.copy:
        content: "{{ result_before.stdout[0] }}"
        dest: "/home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/{{ inventory_hostname }}/\
              show_interfaces_before.log"
        mode: '0644'

    - name: Set description on interfaces
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet eth1 description general_exam_1
          - set interfaces ethernet eth2 description general_exam_2
        save: true

    - name: Show commands after
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
      register: result_after

    - name: Output text file in after_directory
      ansible.builtin.copy:
        content: "{{ result_after.stdout[0] }}"
        dest: "/home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/{{ inventory_hostname }}/\
              show_interfaces_after.log"
        mode: '0644'
