---
- name: Exam2-1
  hosts: localhost
  gather_facts: false

  vars:
    dir_names:
      - { parent: 'before', hosts: 'vyos01'}
      - { parent: 'before', hosts: 'vyos02'}
      - { parent: 'after', hosts: 'vyos01'}
      - { parent: 'after', hosts: 'vyos02'}

  tasks:
    - name: Make Directory
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/{{ item.parent }}/{{ item.hosts }}
        state: directory
        mode: "0755"
      loop: "{{ dir_names }}"
