---
- name: Exam2-3
  hosts: vyos01
  gather_facts: false

  tasks:
    - name: Change vrrp priority on vyos01
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority 255
          - set high-availability vrrp group service_nw02 priority 255
        save: true
      register: result
      ignore_errors: true

    - name: Debug success message
      ansible.builtin.debug:
        msg: "succeeded"
      when: result is succeeded

    - name: Debug fail message
      ansible.builtin.debug:
        msg: "failed"
      when: result is failed
