---
- name: Exam1_other
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Before task
      ansible.builtin.import_role:
        name: exam_1_get_show_command

    - name: Change priority of vrrp
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority 50
          - set high-availability vrrp group service_nw02 priority 50
        save: true
      when: inventory_hostname == 'vyos01'

    - name: After task
      ansible.builtin.import_role:
        name: exam_1_get_show_command
