---
- name: Exam2-1_other
  hosts: localhost
  gather_facts: false

  vars:
    parent_dir:
      - before
      - after
    hosts_dir:
      - vyos01
      - vyos02

  tasks:
    - name: Make Directory
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/{{ item.0 }}/{{ item.1 }}
        state: directory
        mode: "0755"
      loop: "{{ parent_dir | product(hosts_dir) }}"
