---
- name: Change VRRP priority on vyos routers and verify
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Pre-check VRRP status on vyos01 and vyos02
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vyos_show_vrrp
    
    - name: Debug vyos_show_vrrp_before
      ansible.builtin.debug:
        var: vyos_show_vrrp

    - name: Set VRRP priority on vyos01 to 50
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority 50
          - set high-availability vrrp group service_nw02 priority 50
        save: true
      when: inventory_hostname == "vyos01"

    - name: Post-check VRRP status on vyos01 and vyos02
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vyos_show_vrrp
    
    - name: Debug vyos_show_vrrp_after
      ansible.builtin.debug:
        var: vyos_show_vrrp
    
