---
- name: 2-2
  hosts: all
  gather_facts: yes


  tasks:
    - name: show config before
      vyos.vyos.vyos_command:
        commands:
        - show configuration command
      register: result_before
      when: inventory_hostname in ['vyos01','vyos02']

    - name: adddns
      vyos.vyos.vyos_config:
        lines:
          - set system name-server {{item.dns}}
      loop: 
      - { dns: 9.9.9.9 }
      - { dns: 149.112.112.112 }
      - { dns: 2620:fe::fe }
      - { dns: 2620:fe::9 }
      when: inventory_hostname in ['vyos01','vyos02']
#      register: vyos_add-publicdns



    - name: log_touch_before
      ansible.builtin.file:
        #path: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/{{ item.host }}/vyos01_{{ ansible_date_time.iso8601_basic_short }}.log
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/{{ item.host }}/{{ item.host }}_before.log
        state: touch 
      loop: 
      - { host: 'vyos01' }
      - { host: 'vyos02' }
      when: inventory_hostname in ['vyos01','vyos02']

    - name:  log_writing_before
      ansible.builtin.copy:
        content: "{{ result_before.stdout[0] }}"
        #dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/{{ item.host }}/vyos01_{{ ansible_date_time.iso8601_basic_short }}.log
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/{{ item.host }}/{{ item.host }}_before.log
      loop: 
      - { host: 'vyos01' }
      - { host: 'vyos02' }
      when: inventory_hostname in ['vyos01','vyos02']

    - name: show config after
      vyos_command:
        commands:
        - show configuration command
      register: result_after
      when: inventory_hostname in ['vyos01','vyos02']

    - name: log_touch_after
      ansible.builtin.file:
        #path: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/{{ item.host }}/vyos01_{{ ansible_date_time.iso8601_basic_short }}.log
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/{{ item.host }}/{{ item.host }}_after.log
        state: touch 
      loop: 
      - { host: 'vyos01' }
      - { host: 'vyos02' }
      when: inventory_hostname in ['vyos01','vyos02']

    - name:  log_writing_after
      ansible.builtin.copy:
        content: "{{ result_after.stdout[0] }}"
        #dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/{{ item.host }}/vyos01_{{ ansible_date_time.iso8601_basic_short }}.log
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/{{ item.host }}/{{ item.host }}_after.log
      loop: 
      - { host: 'vyos01' }
      - { host: 'vyos02' }
      when: inventory_hostname in ['vyos01','vyos02']

