---
- name: Change VRRP priority on vyos routers and verify
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Pre-check show vrrp on vyos01
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vyos01_before

    - name: Save initial show command output to file for vyos01
      copy:
        content: "{{ vyos01_before.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos01/show_config_before.txt
      when: inventory_hostname == 'vyos01'

    - name: Pre-check show vrrp on vyos02
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vyos02_before

    - name: Save initial show command output to file for vyos02
      copy:
        content: "{{ vyos01_before.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos02/show_config_before.txt
      when: inventory_hostname == 'vyos02'

    - name: Set VRRP priority on vyos01 to 100
      when: inventory_hostname == "vyos01"
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority '100'
          - set high-availability vrrp group service_nw02 priority '100' 
        save: true

    - name: Set VRRP priority on vyos02 to 250
      when: inventory_hostname == "vyos02"
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority '250'
          - set high-availability vrrp group service_nw02 priority '250' 
        save: true

    - name: Pre-check show vrrp on vyos01
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vyos01_after

    - name: Save initial show command output to file for vyos01
      copy:
        content: "{{ vyos01_after.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/vyos01/show_config_after.txt
      when: inventory_hostname == 'vyos01'

    - name: Pre-check show vrrp on vyos02
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vyos02_after

    - name: Save initial show command output to file for vyos02
      copy:
        content: "{{ vyos02_after.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/vyos02/show_config_after.txt
      when: inventory_hostname == 'vyos02'