---
- name: Exam1
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Show VRRP before change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vrrp_before

    - name: Debug VRRP before change
      ansible.builtin.debug:
        var: vrrp_before.stdout_lines

    - name: Change VRRP priority on vyos01
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority 50
          - set high-availability vrrp group service_nw02 priority 50
      when: inventory_hostname == 'vyos01'

    - name: Show VRRP after change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vrrp_after

    - name: Debug VRRP after change
      ansible.builtin.debug:
        var: vrrp_after.stdout_lines

    - name: Ensure directories exist (vyos01)
      file:
        path: "/home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos01"
        state: directory
        mode: '0755'
      when: inventory_hostname == 'vyos01'

    - name: Ensure directories exist (vyos02)
      file:
        path: "/home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos02"
        state: directory
        mode: '0755'
      when: inventory_hostname == 'vyos02'

    - name: Save VRRP status before change (vyos01)
      when: inventory_hostname == 'vyos01'
      ansible.builtin.copy:
        content: "{{ vrrp_before.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos01/vrrp_status_before.txt

    - name: Save VRRP status before change (vyos02)
      when: inventory_hostname == 'vyos02'
      ansible.builtin.copy:
        content: "{{ vrrp_before.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos02/vrrp_status_before.txt

    - name: Save VRRP status after change (vyos01)
      when: inventory_hostname == 'vyos01'
      ansible.builtin.copy:
        content: "{{ vrrp_after.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/vyos01/vrrp_status_after.txt
        
    - name: Save VRRP status after change (vyos02)
      when: inventory_hostname == 'vyos02'
      ansible.builtin.copy:
        content: "{{ vrrp_after.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/vyos02/vrrp_status_after.txt
