---
- name: Exam2-2
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Show VRRP before change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vrrp_before

    - name: Debug VRRP before change
      ansible.builtin.debug:
        var: vrrp_before.stdout_lines

    - name: Save VRRP status before change (vyos01)
      when: inventory_hostname == 'vyos01'
      ansible.builtin.copy:
        content: "{{ vrrp_before.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos01/vrrp_before.txt

    - name: Save VRRP status before change (vyos02)
      when: inventory_hostname == 'vyos02'
      ansible.builtin.copy:
        content: "{{ vrrp_before.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/vyos02/vrrp_before.txt

    - name: Change VRRP priority and description on vyos01
      when: inventory_hostname == 'vyos01'
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group GROUP1 priority 50
          - set interfaces ethernet eth1 description "Changed by Ansible"

    - name: Change VRRP priority and description on vyos02
      when: inventory_hostname == 'vyos02'
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group GROUP1 priority 100
          - set interfaces ethernet eth1 description "Checked by Ansible"

    - name: Show VRRP after change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vrrp_after

    - name: Debug VRRP after change
      ansible.builtin.debug:
        var: vrrp_after.stdout_lines

    - name: Save VRRP status after change (vyos01)
      when: inventory_hostname == 'vyos01'
      ansible.builtin.copy:
        content: "{{ vrrp_after.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/vyos01/vrrp_after.txt

    - name: Save VRRP status after change (vyos02)
      when: inventory_hostname == 'vyos02'
      ansible.builtin.copy:
        content: "{{ vrrp_after.stdout }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/vyos02/vrrp_after.txt