---
- name: Exam2-3
  hosts: vyos01
  gather_facts: false

  tasks:
    - name: Change vrrp priority 255
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority 255
          - set high-availability vrrp group service_nw02 priority 255
        save: true
      register: result
      ignore_errors: true

    - name: Debug message success
      ansible.builtin.debug:
        msg: "success"
      when: result is success

    - name: Debug message fail
      ansible.builtin.debug:
        msg: "fail"
      when: result is fail
