---
- name: Exam2-2
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Show VRRP before change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vrrp_before

    - name: Output VRRP status before change
      ansible.builtin.copy:
        content: "{{ vrrp_before.stdout[0] }}"
        dest: "/home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/before/{{ inventory_hostname }}/show_vrrp_before.log"
        mode: '0644'

    - name: Set VRRP priority and description
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority {{ (inventory_hostname == 'vyos01') | ternary(50, 100) }}
          - set interfaces ethernet eth1 description {{ (inventory_hostname == 'vyos01') | ternary('Changed_by_Ansible', 'Checked_by_Ansible') }}
        save: true

    - name: Show VRRP after change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: vrrp_after

    - name: Output VRRP status after change
      ansible.builtin.copy:
        content: "{{ vrrp_after.stdout[0] }}"
        dest: "/home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/after/{{ inventory_hostname }}/show_vrrp_after.log"
        mode: '0644'
