---
- name: Exam1
  hosts: vyos
  gather_facts: false

  tasks:
    - name: Show VRRP before change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: result

    - name: Debug VRRP before change
      ansible.builtin.debug:
        var: vrrp_before_lines

    - name: Change VRRP priority on vyos01
      vyos.vyos.vyos_config:
        lines:
          - set high-availability vrrp group service_nw01 priority 50
          - set high-availability vrrp group service_nw02 priority 50
        save: true
      when: inventory_hostname == 'vyos01'

    - name: Show VRRP after change
      vyos.vyos.vyos_command:
        commands:
          - show vrrp
      register: result

    - name: Debug VRRP after change
      ansible.builtin.debug:
        var: vrrp_after_lines
