---
- name: Exam2-1
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "/home/ec2-user/ansible_on_vyos/ansible_practice/08_general-practice/{{ item }}"
        state: directory
        mode: '0755'

      loop:
        - before/vyos01
        - before/vyos02
        - after/vyos01
        - after/vyos02