---
- name: vrrp priority change backup
  hosts: vyos
  gather_facts: false

  tasks:
    - name: 
      vyos_command:
        commands:
        - show vrrp detail | grep "Total priority"
 #      - show configuration commands | grep vrrp
 #      - show configuration commands | grep -E 'vrrp|ethernet'
      register: result

    - name: before_priority_chk
      ansible.builtin.debug:
        var: result.stdout_lines

    - name: priority change
      vyos_config:
        lines:
          - set high-availability vrrp group {{item.service_name}} priority {{item.vrrp_priority}}
        save: true
      when: inventory_hostname in ['vyos01']
      loop: 
        - { service_name: 'service_nw01', vrrp_priority: '50' }
        - { service_name: 'service_nw02', vrrp_priority: '50' }
    
    - name:
      vyos_command:
        commands:
        - show vrrp detail | grep "Total priority"
 #      - show configuration commands | grep vrrp
 #      - show configuration commands | grep -E 'vrrp|ethernet'
      register: result

    - name: after_priority_chk
      ansible.builtin.debug:
        var: result.stdout_lines

