---
- name: vrrp priority change backup
  hosts: vyos
  gather_facts: false

  tasks:
    - name:
      vyos_command:
        commands:
        - show vrrp detail | grep "Total priority"
      register: result

    - name: before_priority_chk
      debug:
        var: result.stdout_lines

    - name: priority backup
      vyos_config:
        lines:
          - set high-availability vrrp group {{item.service_name}} priority {{item.vrrp_priority}}
      when: inventory_hostname in ['vyos01']
      loop: 
        - { service_name: 'service_nw01', vrrp_priority: '150' }
        - { service_name: 'service_nw02', vrrp_priority: '150' }
    
    - name:
      vyos_command:
        commands:
        - show vrrp detail | grep "Total priority"
      register: result

    - name: after_priority_chk_backup
      debug:
        var: result.stdout_lines

