---
- name: exam1
  hosts: localhost
  gather_facts: false

  tasks:
    - name: set_fact
      ansible.builtin.set_fact:
        HelIo: "Hello Ansible!"

    - name: debug
      ansible.builtin.debug:
        var: Hello
